### ISSUE TITLE
No package results in nullpointer

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NickstaDB/reflections#102]
```
Executing 

        final Reflections reflections = new Reflections(new ConfigurationBuilder()
                .filterInputsBy(new FilterBuilder().excludePackage(Injector.class))
                .addUrls(ClasspathHelper.forClass(getClass(), application.classloader()))
                .addScanners(
                        new SubTypesScanner(),
                        new TypeAnnotationsScanner(),
                        new ResourcesScanner()
                ));

With no classpath results in nptr:

Caused by: java.lang.NullPointerException: null
    at org.reflections.util.ClasspathHelper.forClass(ClasspathHelper.java:83) ~[reflections-0.9.6.jar:na]
    at Global.beforeStart(Global.java:31) ~[classes/:na]
    at play.core.j.JavaGlobalSettingsAdapter.beforeStart(JavaGlobal.scala:11) ~[play_2.9.1.jar:2.0-RC1-SNAPSHOT]
    at play.api.GlobalPlugin.<init>(Global.scala:128) ~[play_2.9.1.jar:2.0-RC1-SNAPSHO
```

Original issue reported on code.google.com by `mathias....@gmail.com` on 2 Feb 2012 at 9:21

**Comment by GoogleCodeExporter** [comment]
```
I think that's ok
```

Original comment by `ronm...@gmail.com` on 2 May 2012 at 3:47
- Changed state: **WontFix**
