### ISSUE TITLE
Groovy Reflection - Unable to use with Groovy that has been compiled to byte code

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NickstaDB/reflections#151]
```
What steps will reproduce the problem?
1. Write a groovy class with annotation
2. Scan code for annotation 
3. Code fails with exception similar to the below.

What is the expected output? What do you see instead?
Expect the code to be picked up.

java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.qualica.flexifin.common.service.GeneralCoreService.handleServiceRequest(GeneralCoreService.java:67)
        at com.qualica.flexifin.common.service.AbstractCoreService$1.run(AbstractCoreService.java:66)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
        at java.lang.Thread.run(Thread.java:680)
Caused by: org.reflections.ReflectionsException: could not get type for name 
com.qualica.flexifin.hook.AnotherHook
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:378)
        at org.reflections.util.Utils.getMemberFromDescriptor(Utils.java:78)
        at org.reflections.util.Utils.getMethodsFromDescriptors(Utils.java:94)
        at org.reflections.Reflections.getMethodsAnnotatedWith(Reflections.java:396)

What version of the product are you using? On what operating system?
current version.

Please provide any additional information below.

Wrote a custom annotation, annotated a method in the groovy class with this 
annotation. Compiled the groovy down to java bytecode. Then proceeded to get 
the error below.

```

Original issue reported on code.google.com by `NicWille...@gmail.com` on 18 Jul 2013 at 11:22

**Comment by GoogleCodeExporter** [comment]
```
not reproducible. please provide more info. thanks!
```

Original comment by `ronm...@gmail.com` on 5 Jun 2014 at 7:22
