### ISSUE TITLE
Scan Annotations from a URLClassLoader

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NickstaDB/reflections#18]
```
What steps will reproduce the problem? (not a problem)
1.
urlsToLoad = ["http://www......com/jars/archive.jar"]
URLClassLoader loader = URLClassLoader.newInstance(urlsToLoad);

2.
Configuration configuration = new AbstractConfiguration() {
            {
                this.setUrls(urlsToLoad);
//Can use not olny file:// ?

setScanners(new SubTypesScanner(), new ClassAnnotationsScanner());
                setFilter(new IncludeExcludeChain(new
IncludePrefix("com.test.some")));
}



What version of the product are you using? On what operating system?
google-collections 0.9
reflections 0.92
Ubuntu 9 64 
Jdk 1.6_12


Please provide any additional information below.
Here de error:

ang.IllegalArgumentException: URI scheme is not "file"
    at java.io.File.<init>(File.java:366)
    at org.reflections.util.VirtualFile.iterable(VirtualFile.java:77)
```

Original issue reported on code.google.com by `davi.zu...@gmail.com` on 7 May 2009 at 6:20

**Comment by GoogleCodeExporter** [comment]
```
fixed on trunk, VfsTest.HttpDir
```

Original comment by `ronm...@gmail.com` on 28 Nov 2009 at 4:22

**Comment by GoogleCodeExporter** [comment]
Original comment by `ronm...@gmail.com` on 28 Nov 2009 at 4:22
- Changed state: **Fixed**
