### ISSUE TITLE
Add support for JBoss 5 vfs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NickstaDB/reflections#27]
```
Attached a little patch to support reflections within JBoss 5. It basically
reverts the vfszip and vfsfile jboss url to something that common-vfs would
accept. There is also a test class, that needs some resource in
src/test/resources. I don't know how to include them in the patch, but it
should be quite easy to recreate them.

Thanks a lot for the great work (and version 0.9.4 looks like a huge
improvement).

R.
```

Original issue reported on code.google.com by `bara...@gmail.com` on 26 Aug 2009 at 10:53

Attachments:
- [reflections-0.9.4-jbossvfs-patch.txt](https://storage.googleapis.com/google-code-attachments/reflections/issue-27/comment-0/reflections-0.9.4-jbossvfs-patch.txt)

**Comment by GoogleCodeExporter** [comment]
```
I would like to have this fix as soon as possible too since it blocks migration 
to
JBoss 5 for my project.

By the way, I doubt that suggested patch will fix the Reflections.
Could you, please, share patched JAR on any web share to let me check that it 
is OK?

Unfortunately, I can't get sources, patch and compile them myself for some 
reasons.
```

Original comment by `l...@mail.ru` on 4 Sep 2009 at 9:01

**Comment by GoogleCodeExporter** [comment]
```
Here it is, this is the modified version of reflections we are using inside our
organizations. It doesn't contain the source code, but if you need it let me 
know and
I'll generate a source jar.
```

Original comment by `bara...@gmail.com` on 9 Sep 2009 at 4:47

Attachments:
- [reflections-0.9.4-tsb.jar](https://storage.googleapis.com/google-code-attachments/reflections/issue-27/comment-2/reflections-0.9.4-tsb.jar)

**Comment by GoogleCodeExporter** [comment]
```
I checked your fix and it works. Thank you!
So, this fixed JAR can be used for development purposes until this issue is not 
fixed.
```

Original comment by `l...@mail.ru` on 11 Sep 2009 at 10:06

**Comment by GoogleCodeExporter** [comment]
```
the solution is probably to replace common vfs with something better that can 
handle
different resource types in a pluggable manner. suggestions?
```

Original comment by `ronm...@gmail.com` on 11 Sep 2009 at 10:54

**Comment by GoogleCodeExporter** [comment]
```
Uhm... from what I've seen, common VFS looked pretty good to me. A vfs plugin 
could
be created to handle the JBoss VFS, which i believe shouldn't be too complex.
Unfortunately when I created the patch I was in a hurry, and right now I don't 
have
the time needed (although it is in my todo list). So, i wouldn't plan changing 
the
apache vfs, just adding plugins for other resource types.
```

Original comment by `bara...@gmail.com` on 11 Sep 2009 at 2:48

**Comment by GoogleCodeExporter** [comment]
```
a UrlType can be created for org.reflections.vfs.Vfs, that can handle jboss 5 
vfs, a 
patch would be appreciated...
```

Original comment by `ronm...@gmail.com` on 28 Nov 2009 at 4:26

**Comment by GoogleCodeExporter** [comment]
```
Has someone created a working UrlType for this issue. I am trying to get this 
working
the whole day without a solution. I can actually access my EAR file but not the 
JARs
within, so "Reflections" is not able to find any classes. Some help would be
appreciated. Thx
```

Original comment by `lis...@gmail.com` on 7 Apr 2010 at 1:23

**Comment by GoogleCodeExporter** [comment]
```
We are using reflections in JBoss5.1.GA.I have used latest version of 0.9.5-RC2.
Its not working with JBoss5.1 GA.
ERROR [org.reflections.Reflections] (HDScanner) could not create Vfs.Dir from 
url. 
ignoring the exception and continuing.
Is there any fix available with next version?

```

Original comment by `hari...@gmail.com` on 25 May 2010 at 4:11

**Comment by GoogleCodeExporter** [comment]
```
haridcs: it shouldn't be a trouble to implement a Vfs.UrlType for that scenario,
IMHO. kindly try to do that (look at that class and at the corresponding test 
class).
alternatively, supply (either here or via my email) the deployment artifact.
anyways, contributing a patch is appreciated!
```

Original comment by `ronm...@gmail.com` on 25 May 2010 at 6:36

**Comment by GoogleCodeExporter** [comment]
```
I writed a UrlType class based on barakka adapter. 
You must invoke "org.reflections.vfs.Vfs.addDefaultURLTypes(new UrlTypeVFS());" 
to define the default url types to be used by Reflections.

I hope it work for you.

```

Original comment by `sergio.p...@gmail.com` on 6 Jul 2010 at 1:41

Attachments:
- [UrlTypeVFS.java](https://storage.googleapis.com/google-code-attachments/reflections/issue-27/comment-10/UrlTypeVFS.java)

**Comment by GoogleCodeExporter** [comment]
```
thanks for the contribution, sergio.
I will look at it and merge it
```

Original comment by `ronm...@gmail.com` on 7 Jul 2010 at 7:05

**Comment by GoogleCodeExporter** [comment]
```
The current version of UrlTypeVFS still doesn't seem to work on JBoss 5. 
Returning a string from adaptURL results in a failed operation opening the zip 
file.  If a URL is returned, then the URL-based constructor for ZipDir gets 
invoked and is run through normalization -- which works perfectly.

As an interesting side note, the standard process of filtering by class/package 
(using FilterBuilder.Include) breaks down for a zip file.  This is because the 
path that gets analyzed is 
<zipFilePath>!<directoryStructure>/<packageStructure>/MyClass.class rather than 
simply starting with <packageStructure>.  This means that when matcher.matches 
is invoked, it fails to find any matches due to requiring a complete match -- 
and now the path includes the zip file path.  Changing from matcher.matches() 
to matcher.find() would resolve this issue.

In the mean time, I am using FilterBuilder.include with my own regex as a 
work-around.

Attached is a revised version of UrlTypeVFS that I am using.  This is the only 
required change in order for reflections to work on JBoss 5.

```

Original comment by `sage....@gmail.com` on 8 Dec 2010 at 8:58

Attachments:
- [UrlTypeVFS.java](https://storage.googleapis.com/google-code-attachments/reflections/issue-27/comment-12/UrlTypeVFS.java)

**Comment by GoogleCodeExporter** [comment]
```
BTW, in case anyone prefers it as a patch, here is the patch file.

Note that there are a few minor changes I made to formatting; this was to help 
in debugging.

```

Original comment by `sage....@gmail.com` on 8 Dec 2010 at 9:19

Attachments:
- [UrlTypeVFS.patch](https://storage.googleapis.com/google-code-attachments/reflections/issue-27/comment-13/UrlTypeVFS.patch)

**Comment by GoogleCodeExporter** [comment]
```
fixed on trunk
```

Original comment by `ronm...@gmail.com` on 12 May 2011 at 8:28
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Please send the jar with the fix, because i'm not able to compile
```

Original comment by `meneghe...@gmail.com` on 16 Jun 2011 at 1:30

**Comment by GoogleCodeExporter** [comment]
```
I am also getting the dependency error while compiling. A Jar will be 
appreciated.

Thanks
```

Original comment by `neeru.r...@gmail.com` on 16 Jun 2011 at 7:36

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Okie fixed the compilation issues by changing the jboss-maven URL in 
reflections/pom..xml to 
https://repository.jboss.org/nexus/content/groups/public-jboss
```

Original comment by `neeru.r...@gmail.com` on 16 Jun 2011 at 7:55

**Comment by GoogleCodeExporter** [comment]
```
I m using the latest code from trunk. But I dont think this issue is resolved. 
DO we still need to use our own URLType for Jboss?

It is still failing with exception- 
org.reflections.ReflectionsException: could not create Vfs.Dir from url, no 
matching UrlType was found 
[vfszip:/home/auraria/AHS/jboss/server/auraria/deploy/auraria/auraria-service-ti
er.ear/auraria-service-tier.jar/]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the 
static setDefaultURLTypes(final List<UrlType> urlTypes) or 
addDefaultURLTypes(UrlType urlType) with your specialized UrlType
```

Original comment by `neeru.r...@gmail.com` on 16 Jun 2011 at 9:52

**Comment by GoogleCodeExporter** [comment]
Original comment by `ronm...@gmail.com` on 17 Jun 2011 at 5:12
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
added Vfs.DefaultUrlTypes.vfsfile/vfsdir and these should work out of the box 
for jboss5/6. the vfs.JBoss6UrlType is also another option, but now deprecated 
in favor of vfsfile/dir. can you confirm these are working fine?
```

Original comment by `ronm...@gmail.com` on 30 Aug 2011 at 6:55
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
I'm using Reflections 0.9.6 from http://reflections.googlecode.com/svn/repo 
repository in JBoss 5.1.0 but I'm still getting the error:

15:43:12,862 ERROR [STDERR] org.reflections.ReflectionsException: could not 
create Vfs.Dir from url, no matching UrlType was found 
[vfszip:/home/jsanchez/apps/jboss/jboss-5.1.0.GA/server/default/deploy/OHA-RestS
ervices.war/WEB-INF/lib/oha-common-interfaces-1.2.0-SNAPSHOT.jar/]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the 
static setDefaultURLTypes(final List<UrlType> urlTypes) or 
addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
```

Original comment by `getace...@gmail.com` on 27 Oct 2011 at 1:47

**Comment by GoogleCodeExporter** [comment]
```
I'm using JBoss_5_1_0_GA and Reflections 0.9.6 with the UrlTypeVFS.java posted 
in Comment 12 and I am getting the following exception. I'd be grateful if 
anyone could shed some light on it.

19:20:47,022 ERROR [Reflections] could not create Vfs.Dir from url. ignoring 
the exception and continuing
org.reflections.ReflectionsException: could not create Dir using 
com.myapp.UrlTypeVFS@720fe387 from url 
vfszip:/path/to/jboss/server/default/deploy/myApp-1.0-SNAPSHOT.ear/lib/myApp-lib
-1.0-SNAPSHOT.jar/
    at org.reflections.vfs.Vfs.fromURL(Vfs.java:100)
    at org.reflections.vfs.Vfs.fromURL(Vfs.java:90)
    at org.reflections.Reflections.scan(Reflections.java:211)
    at org.reflections.Reflections.<init>(Reflections.java:103)
    at org.reflections.Reflections.<init>(Reflections.java:134)
    at org.reflections.Reflections.<init>(Reflections.java:117)
    ...
Caused by: java.lang.RuntimeException: java.util.zip.ZipException: error in 
opening zip file
    at org.reflections.vfs.ZipDir.<init>(ZipDir.java:27)
    at com.myapp.UrlTypeVFS.createDir(UrlTypeVFS.java:54)
    at org.reflections.vfs.Vfs.fromURL(Vfs.java:98)
    ... 134 more
Caused by: java.util.zip.ZipException: error in opening zip file
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.<init>(ZipFile.java:127)
    at java.util.zip.ZipFile.<init>(ZipFile.java:88)
    at org.reflections.vfs.ZipDir.<init>(ZipDir.java:26)
    ... 136 more
19:20:47,026  INFO  [Reflections] Reflections took 33 ms to scan 7 urls, 
producing 0 keys and 0 values

Thanks
```

Original comment by `jjlharri...@gmail.com` on 26 Apr 2012 at 6:26

**Comment by GoogleCodeExporter** [comment]
```
I added some changes to get it working on JBoss 5.1.0.

An error was being thrown because with the existing code shown here: 
http://code.google.com/p/reflections/source/browse/trunk/reflections/src/main/ja
va/org/reflections/vfs/UrlTypeVFS.java

It was failing for me when it tried to process a directory, so I combined the 
changes with what was done in Wiki portion with the file written by the guy on 
comment 12.

```

Original comment by `ryan2...@gmail.com` on 10 Jan 2013 at 10:00

Attachments:
- [UrlTypeVFS.java](https://storage.googleapis.com/google-code-attachments/reflections/issue-27/comment-24/UrlTypeVFS.java)

**Comment by GoogleCodeExporter** [comment]
```
In which version was this fixed? I'm using 0.9.9-RC1 and still seeing the error.
Thanks
```

Original comment by `theonlya...@gmail.com` on 21 Jan 2015 at 6:46

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I also saw the same problem in 0.9.9-RC1. Then I suddenly discovered that I had 
at some earlier time added reflections-0.9.5.1 to jboss-as/common/lib which was 
what lead to my problem. I was loading an older version!
```

Original comment by `thomassa...@gmail.com` on 21 Jan 2015 at 10:17
