### ISSUE TITLE
'org.reflections:reflections-maven' not found in repository: Unable to download the artifact

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NickstaDB/reflections#28]
```
What steps will reproduce the problem?
1.
Add 
      <plugin>
        <groupId>org.reflections</groupId>
        <artifactId>reflections-maven</artifactId>
        <version>0.9</version>
        <executions>
          <execution>
            <goals>
              <goal>reflections</goal>
            </goals>
            <phase>process-classes</phase>
          </execution>
        </executions>
      </plugin>
 to my maven build section
2. include the reflections-maven jar in my local repository
3. run mvn -e install

What is the expected output? What do you see instead?

I expect the task to run - instead i get :

+ Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] --------------------------------------------------------------------
----
[INFO] Building test
[INFO]    task-segment: [clean, install]
[INFO] --------------------------------------------------------------------
----
Downloading: http://repo1.maven.org/maven2/org/reflections/reflections-
maven/0.9.4/reflections-maven-0.9.4.pom
[INFO] Unable to find resource 'org.reflections:reflections-
maven:pom:0.9.4' in repository central (http://repo1.ma
ven.org/maven2)
Downloading: http://repo1.maven.org/maven2/org/reflections/reflections-
maven/0.9.4/reflections-maven-0.9.4.pom
[INFO] Unable to find resource 'org.reflections:reflections-
maven:pom:0.9.4' in repository central (http://repo1.ma
ven.org/maven2)
[INFO] --------------------------------------------------------------------
----
[ERROR] BUILD ERROR
[INFO] --------------------------------------------------------------------
----
[INFO] Error building POM (may not be this project's POM).


Project ID: org.reflections:reflections-maven

Reason: POM 'org.reflections:reflections-maven' not found in repository: 
Unable to download the artifact from any r
epository

  org.reflections:reflections-maven:pom:0.9.4

from the specified remote repositories:
  central (http://repo1.maven.org/maven2)

 for project org.reflections:reflections-maven


[INFO] --------------------------------------------------------------------
----
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Unable to build 
project for plugin 'org.reflections:reflect
ions-maven': POM 'org.reflections:reflections-maven' not found in 
repository: Unable to download the artifact from
any repository

  org.reflections:reflections-maven:pom:0.9.4

from the specified remote repositories:
  central (http://repo1.maven.org/maven2)

 for project org.reflections:reflections-maven
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.verifyPlugin
(DefaultLifecycleExecutor.java:1557)
        at 
org.apache.maven.lifecycle.DefaultLifecycleExecutor.bindPluginToLifecycle
(DefaultLifecycleExecutor.java:
1503)
        at 
org.apache.maven.lifecycle.DefaultLifecycleExecutor.constructLifecycleMappi
ngs(DefaultLifecycleExecutor.
java:1282)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal
(DefaultLifecycleExecutor.java:534)
        at 
org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFai
lures(DefaultLifecycleExecuto
r.java:387)
        at 
org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments
(DefaultLifecycleExecutor.java:34
8)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute
(DefaultLifecycleExecutor.java:180)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
        at org.apache.maven.cli.compat.CompatibleMain.main
(CompatibleMain.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke
(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke
(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.classworlds.Launcher.launchEnhanced
(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode
(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.InvalidPluginException: Unable to build 
project for plugin 'org.reflections:refl
ections-maven': POM 'org.reflections:reflections-maven' not found in 
repository: Unable to download the artifact fr
om any repository

  org.reflections:reflections-maven:pom:0.9.4

from the specified remote repositories:
  central (http://repo1.maven.org/maven2)

 for project org.reflections:reflections-maven
        at 
org.apache.maven.plugin.DefaultPluginManager.checkRequiredMavenVersion
(DefaultPluginManager.java:293)
        at 
org.apache.maven.plugin.DefaultPluginManager.verifyVersionedPlugin
(DefaultPluginManager.java:205)
        at org.apache.maven.plugin.DefaultPluginManager.verifyPlugin
(DefaultPluginManager.java:184)
        at 
org.apache.maven.plugin.DefaultPluginManager.loadPluginDescriptor
(DefaultPluginManager.java:1642)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.verifyPlugin
(DefaultLifecycleExecutor.java:1540)
        ... 18 more
Caused by: org.apache.maven.project.ProjectBuildingException: 
POM 'org.reflections:reflections-maven' not found in
repository: Unable to download the artifact from any repository

  org.reflections:reflections-maven:pom:0.9.4

from the specified remote repositories:
  central (http://repo1.maven.org/maven2)

 for project org.reflections:reflections-maven
        at 
org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository
(DefaultMavenProjectBuilder.j
ava:605)
        at 
org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository
(DefaultMavenProjectBuilder.java:
251)
        at 
org.apache.maven.plugin.DefaultPluginManager.checkRequiredMavenVersion
(DefaultPluginManager.java:277)
        ... 22 more
Caused by: org.apache.maven.artifact.resolver.ArtifactNotFoundException: 
Unable to download the artifact from any r
epository

  org.reflections:reflections-maven:pom:0.9.4

from the specified remote repositories:
  central (http://repo1.maven.org/maven2)


        at 
org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve
(DefaultArtifactResolver.java:228)
        at 
org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve
(DefaultArtifactResolver.java:90)
        at 
org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository
(DefaultMavenProjectBuilder.j
ava:558)
        ... 24 more
Caused by: org.apache.maven.wagon.ResourceDoesNotExistException: Unable to 
download the artifact from any repositor
y
        at 
org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact
(DefaultWagonManager.java:404)
        at 
org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve
(DefaultArtifactResolver.java:216)
        ... 26 more
[INFO] --------------------------------------------------------------------
----
[INFO] Total time: 2 seconds
[INFO] Finished at: Sat Sep 05 09:48:14 BST 2009
[INFO] Final Memory: 2M/4M
[INFO] --------------------------------------------------------------------
----
C:\Users\russell\workspace\webconsole>

What version of the product are you using? On what operating system?
0.9 of the reflections-maven and 0.9.4 of reflections.
maven 2.2.1
java 1_6_0_02

Please provide any additional information below.
If i remove the build target then the maven pom can find the jar files 
okay but as soons as I add the build command it crashes. Any ideas?

```

Original issue reported on code.google.com by `rugor...@gmail.com` on 5 Sep 2009 at 8:53

**Comment by GoogleCodeExporter** [comment]
```
fixed on trunk
```

Original comment by `ronm...@gmail.com` on 28 Nov 2009 at 4:20
- Changed state: **Fixed**
