### ISSUE TITLE
jars not being inspected properly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NickstaDB/reflections#30]
```
What steps will reproduce the problem?
1. Configure a Reflections instance as:
        Reflections reflections = new Reflections(new AbstractConfiguration()
        {
            {
                Predicate<String> filter = new FilterBuilder().include(".*");
                setFilter(filter);
                String jarName = "jar:file://"+(new
File(classRepo)).toURL().getPath()+"!/";
                setUrls(Arrays.asList(new URL[] { new URL(jarName) }));
                setScanners(new MethodAnnotationsScanner());
            }
        });

Where classRepo is a final String representing a relative path to a jar. 
The constructor will fail with an NPE:
Exception in thread "main" java.lang.NullPointerException
    at com.google.common.collect.Lists.newArrayList(Lists.java:89)
    at
org.reflections.adapters.ParallelStrategyHelper.apply(ParallelStrategyHelper.jav
a:39)
    at org.reflections.Reflections.scan(Reflections.java:156)
    at org.reflections.Reflections.<init>(Reflections.java:106)
    at
com.sas.perfUnit.framework.PerformanceTester.startTests(PerformanceTester.java:7
6)
    at
com.sas.perfUnit.framework.PerformanceTester.startTests(PerformanceTester.java:7
1)
    at
com.sas.perfUnit.framework.PerformanceTester.main(PerformanceTester.java:43)

What is the expected output? What do you see instead?
I expect for the call to work, resulting in a log message like Reflections
took 375 ms to scan 1 urls, producing 6 keys and 210 values [using 2 cores]
[1 ms per value]

What version of the product are you using? On what operating system?
Latest in the trunk.

Please provide any additional information below.
Looks like Reflections uses URL.getPath around line 150.  That causes the
jar: to get knocked off, but the '!' character at the end stays (resulting
in a bad file URL).  Using URL.toString instead fixes the issue.  This
should probably be tested with jars over a protocol other than file:///
just to be safe.

```

Original issue reported on code.google.com by `Brian.Sw...@sas.com` on 5 Oct 2009 at 10:01

Attachments:
- [URL.patch](https://storage.googleapis.com/google-code-attachments/reflections/issue-30/comment-0/URL.patch)

**Comment by GoogleCodeExporter** [comment]
```
I get the same error message with even a more simple invocation:

Reflections reflections = new Reflections("my.package");  

I have two jars with some classes in the package "my.package". When I load them 
for
testing with maven I get the same error message:

java.lang.NullPointerException
    at com.google.common.collect.Lists.newArrayList(Lists.java:89)
    at org.reflections.adapters.ParallelStrategyHelper.apply(ParallelStrategyHelper.java:39)
    at org.reflections.Reflections.scan(Reflections.java:155)
    at org.reflections.Reflections.<init>(Reflections.java:106)
    at org.reflections.Reflections.<init>(Reflections.java:114)
    at ...
```

Original comment by `abel.cue...@gmail.com` on 12 Nov 2009 at 8:51

**Comment by GoogleCodeExporter** [comment]
```
FYI, the patch worked for me.  thanks for providing it.
```

Original comment by `wesandevie` on 16 Nov 2009 at 8:46

**Comment by GoogleCodeExporter** [comment]
```
fixed on trunk
```

Original comment by `ronm...@gmail.com` on 28 Nov 2009 at 4:18
- Changed state: **Fixed**
