### ISSUE TITLE
org.reflections.ReflectionsException: could not resolve type long[]

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NickstaDB/reflections#33]
```
What steps will reproduce the problem?
1. Create an example class:

package org.example;

public class Example
{
   @Deprecated
   public void printIds(long[] ids) {
      for (long id : ids) {
         System.out.println("id = " + id);
      }
   }
}

2. Create an ExampleTest class:

package org.example;

import org.junit.Test;
import org.reflections.Reflections;
import org.reflections.scanners.MethodAnnotationsScanner;
import org.reflections.util.AbstractConfiguration;
import org.reflections.util.ClasspathHelper;

import java.lang.reflect.Method;
import java.util.Set;

public class ExampleTest
{
   @Test
   public void test()
      throws Exception
   {
      Reflections reflections = new Reflections(new AbstractConfiguration() 
{{
         setUrls(ClasspathHelper.getUrlsForPackagePrefix("org.example"));
         setScanners(new MethodAnnotationsScanner());
      }});
      Set<Method> methods = 
reflections.getMethodsAnnotatedWith(Deprecated.class);
      for (Method method : methods) {
         System.out.println("method.getName() = " + method.getName());
      }
   }
}


3. Run the test

What is the expected output? What do you see instead?
I expect to see "printIds" printed to standard out.  Instead I get:

Nov 17, 2009 1:22:40 PM org.reflections.Reflections scan
INFO: Reflections took 375 ms to scan 1 urls, producing 2 keys and 2 values 
[using 2 cores] [187 ms per value]

org.reflections.ReflectionsException: could not resolve type long[]
    at 
org.reflections.util.DescriptorHelper.resolveType(DescriptorHelper.java:129
)
    at org.reflections.util.Utils.forNames(Utils.java:30)
    at 
org.reflections.Reflections.getMethodFromDescriptor(Reflections.java:544)
    at 
org.reflections.Reflections.getMethodsAnnotatedWith(Reflections.java:379)
    at org.example.ExampleTest.test(ExampleTest.java:25)
<snip>
Caused by: java.lang.ClassNotFoundException: long
    at java.net.URLClassLoader$1.run(URLClassLoader.java:200)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
    at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:169)
    at 
org.reflections.util.DescriptorHelper.resolveType(DescriptorHelper.java:127
)
    ... 32 more


What version of the product are you using? On what operating system?
0.9.4, Windows XP

```

Original issue reported on code.google.com by `nathan.w...@gmail.com` on 17 Nov 2009 at 7:29

**Comment by GoogleCodeExporter** [comment]
```
fixed on trunk
```

Original comment by `ronm...@gmail.com` on 28 Nov 2009 at 4:18
- Changed state: **Fixed**
