### ISSUE TITLE
Using the context classloader in Utils.java

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NickstaDB/reflections#34]
```
The Utils.java class uses the System classloader when returning a Set of
scanned classes. It is possible to obtain the Set<String> of class names
implementing a particular interface from the store and create class
instances using a separate classloader. It would be nice if the library
handled it.

One line change in Utils.java takes care of this.

What steps will reproduce the problem?
0. Create SomeInterface.class and create an implementing class.
1. Create a class/jar of the implementing and do NOT add it to the
classpath of the application using reflections.
2. Create a new class loader (extending URLClassLoader) with the URL of the
new jar
2. Set the current classloader to the one created in 2 by
Thread.currentThread().setContextClassLoader
3. Pass the urls to Reflections instance using ConfigurationBuilder
4. Call a method on the reflections instance e.g.
getSubTypesOf(SomeInterface.class)

This is a scenario for dynamic class loading and invoking an implementation.

Output:
Exception in thread "main" java.lang.RuntimeException:
java.lang.ClassNotFoundException: com.test.SomeInterfaceImpl
    at org.reflections.util.Utils.forName(Utils.java:41)
    at org.reflections.util.Utils.forNames(Utils.java:55)
    at org.reflections.Reflections.getSubTypesOf(Reflections.java:222)


Changing the line 39 in Utils.java to:

return Class.forName(type, true,
Thread.currentThread().getContextClassLoader());

loads the class correctly.

```

Original issue reported on code.google.com by `rohit.ku...@gmail.com` on 1 Dec 2009 at 4:36

**Comment by GoogleCodeExporter** [comment]
```
Somehow, I can't change the Type to Enhancement. Please treat this as an 
enhancement.
```

Original comment by `rohit.ku...@gmail.com` on 1 Dec 2009 at 4:39

**Comment by GoogleCodeExporter** [comment]
```
This happens for me too, under Grails (a case of classloader manipulation as 
described above).

It's enough to do

return Class.forName(type, false, 
Thread.currentThread().getContextClassLoader());

i.e., the class does not need to be initialized.
```

Original comment by `vges...@gmail.com` on 1 Dec 2009 at 11:54

**Comment by GoogleCodeExporter** [comment]
```
fixed on trunk
```

Original comment by `ronm...@gmail.com` on 4 Dec 2009 at 11:18

**Comment by GoogleCodeExporter** [comment]
Original comment by `ronm...@gmail.com` on 17 May 2010 at 4:21
- Changed state: **Done**
