### ISSUE TITLE
no matching UrlType was found [file:/System/Library/Java/Extensions/libAppleScriptEngine.jnilib]

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NickstaDB/reflections#41]
```
What steps will reproduce the problem?

Scala code:

new Reflections(new ConfigurationBuilder()
                .filterInputsBy(new
FilterBuilder().include(".*").exclude("java.*").exclude("scala.*"))
                .setScanners(new SubTypesScanner)
                .setUrls(ClasspathHelper.getUrlsForCurrentClasspath))
            .getStore.getSubTypesOf(classOf[RunOnBoot].getName).iterator


What is the expected output? What do you see instead?

xception in thread "main" org.reflections.ReflectionsException: could not
create Dir from url, no matching UrlType was found
[file:/System/Library/Java/Extensions/libAppleScriptEngine.jnilib]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the
static setDefaultURLTypes(final List<UrlType> urlTypes) or
addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
    at org.reflections.vfs.Vfs.fromURL(Vfs.java:102)
    at org.reflections.vfs.Vfs.fromURL(Vfs.java:87)
    at org.reflections.Reflections.scan(Reflections.java:133)
    at org.reflections.Reflections.<init>(Reflections.java:90)
    at
se.scalablesolutions.akka.BootableRunOnBootService$class.onLoad(BootableRunOnBoo
tService.scala:16)
    at
se.scalablesolutions.akka.Kernel$Bundles$.se$scalablesolutions$akka$comet$Bootab
leCometActorService$$super$onLoad(Kernel.scala:31)
    at
se.scalablesolutions.akka.comet.BootableCometActorService$class.onLoad(BootableC
ometActorService.scala:29)
    at se.scalablesolutions.akka.Kernel$Bundles$.onLoad(Kernel.scala:31)
    at se.scalablesolutions.akka.Kernel$.boot(Kernel.scala:46)
    at se.scalablesolutions.akka.Kernel$.boot(Kernel.scala:36)
    at se.scalablesolutions.akka.Main$.main(Kernel.scala:15)
    at se.scalablesolutions.akka.Main.main(Kernel.scala)



What version of the product are you using? On what operating system?
0.9.5-RC1
OSX 10.5.7
Scala 2.7.7

Please provide any additional information below.

```

Original issue reported on code.google.com by `viktor.k...@gmail.com` on 23 Jan 2010 at 12:13

**Comment by GoogleCodeExporter** [comment]
```
I solved it through after-treating the results generated by 
getUrlsForCurrentClassPath.

protected def classPath() = for {u <- 
ClasspathHelper.getUrlsForCurrentClasspath.asScala;
v <- Vfs.getDefaultUrlTypes.asScala.find(_.matches(u)) } yield u
```

Original comment by `viktor.k...@gmail.com` on 23 Jan 2010 at 1:06

**Comment by GoogleCodeExporter** [comment]
Original comment by `ronm...@gmail.com` on 17 May 2010 at 4:21
- Changed state: **Done**
