### ISSUE TITLE
NoSuchMethodException when looking for non-public methods

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NickstaDB/reflections#62]
```
What steps will reproduce the problem?
1. Create annotation @A, class C and protected method C.m() annotated with @A.
2. Use Reflections to find methods annotated with @A (use appropriate package 
path, use MethodAnnotationsScanner and getMethodsAnnotatedWith).

What is the expected output? What do you see instead?
Reflections should find the protected method C.m(), but it fails with 
NoSuchMethodException instead.

What version of the product are you using? On what operating system?
0.9.5-RC2, Windows 7.

Please provide any additional information below.
Exception in thread "main" org.reflections.ReflectionsException: Can't resolve 
method named m
    at org.reflections.util.Utils.getMethodFromDescriptor(Utils.java:123)
    at org.reflections.Reflections.getMethodsAnnotatedWith(Reflections.java:324)
    ...
Caused by: java.lang.NoSuchMethodException: 
com.naviexpert.maps.map_layers.ram.RamLayer.wrapModifiableInternal()
    at java.lang.Class.getMethod(Class.java:1605)
    at org.reflections.util.Utils.getMethodFromDescriptor(Utils.java:120)
    ... 2 more

```

Original issue reported on code.google.com by `tpreal` on 3 Dec 2010 at 12:46

**Comment by GoogleCodeExporter** [comment]
```
fixed on trunk
```

Original comment by `ronm...@gmail.com` on 12 May 2011 at 7:49
- Changed state: **Fixed**
