### ISSUE TITLE
Store multi-map should be synchronous for multi-threaderd scanning

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NickstaDB/reflections#68]
```
What steps will reproduce the problem?
1. Create a Reflections object with a multi-threaded executor
2. Scan

What is the expected output? What do you see instead?
I get an exception occasionally that reads:

[internal stack]
Caused by: java.util.concurrent.ExecutionException:
java.util.ConcurrentModificationException
       at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:222)
       at java.util.concurrent.FutureTask.get(FutureTask.java:83)
       at org.reflections.Reflections.scan(Reflections.java:162)
       at org.reflections.Reflections.<init>(Reflections.java:92)
       ... 103 more
Caused by: java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:977)
       at java.util.HashMap$KeyIterator.next(HashMap.java:1012)
       at java.util.HashMap.buildCache(HashMap.java:590)
       at java.util.HashMap.resize(HashMap.java:576)
       at java.util.HashMap.addEntry(HashMap.java:939)
       at java.util.HashMap.put(HashMap.java:477)
       at java.util.HashSet.add(HashSet.java:200)
       at
com.google.common.collect.StandardMultimap.put(StandardMultimap.java:
194)
       at
com.google.common.collect.StandardSetMultimap.put(StandardSetMultimap.java:
80)
       at
org.reflections.scanners.TypeAnnotationsScanner.scan(TypeAnnotationsScanner.java
:
17)
       at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:
39)
       at org.reflections.Reflections$2.run(Reflections.java:149)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:
442)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
       at java.util.concurrent.FutureTask.run(FutureTask.java:139)
       at java.util.concurrent.ThreadPoolExecutor
$Worker.runTask(ThreadPoolExecutor.java:886)
       at java.util.concurrent.ThreadPoolExecutor
$Worker.run(ThreadPoolExecutor.java:909)
       at java.lang.Thread.run(Thread.java:619)

What version of the product are you using? On what operating system?
0.9.5-RC2

Please provide any additional information below.
My scanner set up is:
new Reflections(new ConfigurationBuilder()
    .setUrls(ClasspathHelper.getUrlsForPackagePrefix("com.qualys"))
        .setScanners(
            new TypeAnnotationsScanner(),
            new PackageScanner())
        .setExecutorServiceSupplier(new Supplier<ExecutorService>() {
            @Override
            public ExecutorService get() {
                return Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors());
                }
            }));

```

Original issue reported on code.google.com by `steve.sk...@gmail.com` on 12 Jan 2011 at 5:43

**Comment by GoogleCodeExporter** [comment]
```
fixed on trunk
```

Original comment by `ronm...@gmail.com` on 12 May 2011 at 7:49
- Changed state: **Fixed**
