### ISSUE TITLE
Error in Oracle Weblogic 10gR3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NickstaDB/reflections#79]
```
What steps will reproduce the problem?
I use reflections jar with ZK framework. When I start server, it show this 
error.

18:04:14.835 [[STANDBY] ExecuteThread: '5' for queue: 'weblogic.kernel.Default 
(self-tuning)'] ERROR org.reflections.Reflections - could not create Vfs.Dir 
from url. ignoring the exception and continuing
org.reflections.ReflectionsException: could not create Dir using 
org.reflections.vfs.Vfs$DefaultUrlTypes$1 from url 
file:/E:/bea/WLSERV~1.3/server/lib/weblogic_sp.jar
    at org.reflections.vfs.Vfs.fromURL(Vfs.java:98)
    at org.reflections.vfs.Vfs.fromURL(Vfs.java:88)
    at org.reflections.Reflections.scan(Reflections.java:199)
    at org.reflections.Reflections.<init>(Reflections.java:91)
    at org.zkoss.spring.web.context.CoreContextListener.preprocessSpringBeansForZKComponentinjection(CoreContextListener.java:107)
    at org.zkoss.spring.web.context.CoreContextListener.contextInitialized(CoreContextListener.java:71)

What is the expected output? What do you see instead?
No error.

What version of the product are you using? On what operating system?
reflections-0.9.5.jar
Oracle Weblogic Server 10gR3

Please provide any additional information below.

```

Original issue reported on code.google.com by `pp.jun...@gmail.com` on 7 Jul 2011 at 11:28

**Comment by GoogleCodeExporter** [comment]
```
fixed on trunk. wonder if the real exception is environment issue or 
reflections issue. can you tell?
```

Original comment by `ronm...@gmail.com` on 30 Aug 2011 at 6:50

**Comment by GoogleCodeExporter** [comment]
Original comment by `ronm...@gmail.com` on 30 Aug 2011 at 6:58
- Changed state: **Fixed**
