### ISSUE TITLE
Error when white space in the paths

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NickstaDB/reflections#87]
```
Looks like the scanner have some issue finding jar located in a folder 
containing a white space.

What steps will reproduce the problem?

I have an webapp in Jetty which is located in a folder containing a white space.

What is the expected output? What do you see instead?

I get a lot of error like the following:

2011-09-08 16:02:56,793 [main] ERROR o.r.Reflections                - could not 
create Vfs.Dir from url. ignoring the exception and continuing 
org.reflections.ReflectionsException: could not create Dir using 
org.reflections.vfs.Vfs$DefaultUrlTypes$2 from url 
jar:file:/home/tuska/XWiki%20Enterprise/webapps/xwiki/WEB-INF/lib/wagon-provider
-api-1.0-beta-6.jar!/
    at org.reflections.vfs.Vfs.fromURL(Vfs.java:98) ~[reflections-0.9.5.jar:na]
    at org.reflections.vfs.Vfs.fromURL(Vfs.java:88) ~[reflections-0.9.5.jar:na]
    at org.reflections.Reflections.scan(Reflections.java:199) [reflections-0.9.5.jar:na]
    at org.reflections.Reflections.<init>(Reflections.java:91) [reflections-0.9.5.jar:na]

If I make sure none of the parent folders contains white spaces I don't get any 
message.

What version of the product are you using? On what operating system?

0.9.5

Please provide any additional information below.

```

Original issue reported on code.google.com by `thomas.m...@gmail.com` on 8 Sep 2011 at 2:16

**Comment by GoogleCodeExporter** [comment]
```
Seems like this comes from a known problem in java.net.URL which is fixed in 
java.net.URI
@see http://stackoverflow.com/questions/724043
@see http://download.oracle.com/javase/6/docs/api/java/net/URI.html

Clean solution would probably be to change the API to use URI.
```

Original comment by `klaus.sc...@gmail.com` on 9 Sep 2011 at 8:12

**Comment by GoogleCodeExporter** [comment]
```
Oh and for a workaround for your problem: Try providing URLs you get via the 
deprecated File.toURL() method, which will not escape illegal URL characters 
such as whitespaces.
```

Original comment by `klaus.sc...@gmail.com` on 9 Sep 2011 at 8:28

**Comment by GoogleCodeExporter** [comment]
```
Note that i get the urls using org.reflections.util.ClasspathHelper#forPackage
```

Original comment by `thomas.m...@gmail.com` on 9 Sep 2011 at 12:09

**Comment by GoogleCodeExporter** [comment]
```
Without changing the whole API you could simply fix 
org.reflections.vfs.ZipDir#ZipDir(URL url) that should unescape what it gets 
from url.getPath() since the fact that URL does not return unescaped parts is 
documented and is not a bug even if that's not very nice.
```

Original comment by `thomas.m...@gmail.com` on 9 Sep 2011 at 12:59

**Comment by GoogleCodeExporter** [comment]
```
Thank you Thomas, i modified org.reflections.vfs.ZipDir#ZipDir(URL url) class 
to fix this issue. Attached is the updated jar.
```

Original comment by `asha.tha...@gmail.com` on 19 Sep 2011 at 5:17

Attachments:
- [reflections-0.9.5-yale.jar](https://storage.googleapis.com/google-code-attachments/reflections/issue-87/comment-5/reflections-0.9.5-yale.jar)

**Comment by GoogleCodeExporter** [comment]
```
Cool thanks will try that for now, when do you plan to release a 0.9.6 or 
something like that ?
```

Original comment by `thomas.m...@gmail.com` on 19 Sep 2011 at 5:28

**Comment by GoogleCodeExporter** [comment]
```
BTW I noticed but did not looked at it closely yet that 
ClasspathHelper#forPackage (and probably other ClasspathHelper methods) 
sometime return valid URLs (with characters like white space escaped) and 
sometimes not.
```

Original comment by `thomas.m...@gmail.com` on 19 Sep 2011 at 5:29

**Comment by GoogleCodeExporter** [comment]
```
Even I got error what you got, just followed the steps you mentioned and it 
worked. So i am contributing the latest code. I am not part of releasing team.
```

Original comment by `asha.tha...@gmail.com` on 19 Sep 2011 at 11:33

**Comment by GoogleCodeExporter** [comment]
```
patches are welcomed :)
```

Original comment by `ronm...@gmail.com` on 20 Sep 2011 at 5:34

**Comment by GoogleCodeExporter** [comment]
```
Here is a patch that make ZipDir support more or less properly URLs.

I did the decode in ZipDir(String p) and not in ZipDir(URL url) since looks 
like it expect to get URLs as String sometimes (which seems a bit messy to me).
```

Original comment by `thomas.m...@gmail.com` on 22 Sep 2011 at 1:29

Attachments:
- [87.patch](https://storage.googleapis.com/google-code-attachments/reflections/issue-87/comment-10/87.patch)

**Comment by GoogleCodeExporter** [comment]
```
Im also experiencing the problem, it does work in RC2 but not in the release of 
0.9.5.

```

Original comment by `nino.mar...@gmail.com` on 28 Sep 2011 at 7:27

**Comment by GoogleCodeExporter** [comment]
```
Any news on when this will be applied and released ? It's not very nice to have 
a library about URL scanning which does not properly support URLs...
```

Original comment by `thomas.m...@gmail.com` on 29 Sep 2011 at 9:42

**Comment by GoogleCodeExporter** [comment]
```
on trunk
```

Original comment by `ronm...@gmail.com` on 30 Sep 2011 at 12:08

**Comment by GoogleCodeExporter** [comment]
```
could we have new release which included this fix.. This is blocking our 
release.. 
```

Original comment by `nino.mar...@gmail.com` on 27 Oct 2011 at 9:26

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Looks like it's on maven central, cool. Thanks for the indirect remainder, will 
update my dependencies :)
```

Original comment by `thomas.m...@gmail.com` on 27 Oct 2011 at 9:49

**Comment by GoogleCodeExporter** [comment]
```
shouldn't this issue be closed ?
```

Original comment by `thomas.m...@gmail.com` on 27 Oct 2011 at 9:49

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
Original comment by `ronm...@gmail.com` on 26 Dec 2011 at 11:26
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
The fix that has been applied here (UTF-8 decoding the URL) fixed the 
whitespace problem, but it introduced a new issue: When a file or path contains 
a plus sign it will be incorrectly decoded into a space character. The reason 
for this that the URLDecoder expects an HTML form 
(application/x-www-form-urlencoded) encoded String. 

The simplest solution would be to just escape the plus sign:
URLDecoder.decode(urlString.replaceAll("\\+", "%2b"), "UTF-8"))

I ran into this with a temporary path on Mac OS X when deploying to Jetty.
```

Original comment by `christia...@gmail.com` on 5 Jan 2012 at 1:24

**Comment by GoogleCodeExporter** [comment]
```
In Version 0.9.8 the issue still exits. I added a Jar in folder "./lib/spa 
ce/my.jar" and I'm receiving the "could not create Dir using jarFile from url 
file:" exception.
```

Original comment by `mis...@gmx.at` on 15 Aug 2012 at 6:33

**Comment by GoogleCodeExporter** [comment]
```
Following Test reproduce the problem:

@Test public void dirWithSpaces_Jar() {
        Set<URL> urls = ClasspathHelper.forPackage("D:/project/lib/spa ce/my.jar");
        assertFalse(urls.isEmpty());
        for (URL url : urls) {
            testVfsDir(url);
        }
    }
```

Original comment by `mis...@gmx.at` on 15 Aug 2012 at 7:03
